import configparser

# read the current config options
config=configparser.ConfigParser()
config.read(<path-to-config.ini>)

# config can be though as a dictionary of dictionaries

# Access the values:
# (if section/key_value is not defined, a KeyError is raised)
config_value = config['<SECTION>']['<key_value>']

# Or re-assign new values:
config['<SECTION>'] = {}
config['<SECTION>']['<key_value>'] = <value>

# to save the changes simply run
with open(<path-to-config.ini>) as f:
    config.write(f)